export const INTENTS = {
  employment: {
    label: 'Трудово право',
    priority: 'high',
    strongPhrases: {
      'uvolniha me': 11,
      'disciplinarno uvolnenie': 12,
      'zapoved za uvolnenie': 11,
      'ne mi plashtat zaplata': 11,
      'ne mi platiha zaplata': 11,
      'trudov dogovor': 8,
      'rabota bez dogovor': 10,
      'inspektsiya po truda': 8,
    },
    coreTerms: {
      uvoln: 6,
      rabotodatel: 5,
      shefa: 4,
      trudov: 5,
      zaplata: 5,
      plasht: 5,
      bolnichen: 4,
      predizvestie: 4,
      disciplinar: 5,
    },
    supportingTerms: {
      zapoved: 3,
      dogovor: 2,
      fish: 2,
      otpusk: 3,
      obyasneniya: 3,
      srok: 2,
    },
    exclusions: {
      'dogovor za naem': -9,
      'dogovor za kredit': -9,
      'notarialen akt': -8,
    },
    subtypes: {
      disciplinaryDismissal: {
        label: 'дисциплинарно уволнение',
        phrases: ['disciplinarno uvolnenie', 'uvolniha me disciplinarno', 'zapoved za disciplinarno', 'disciplinarno nakazanie'],
        stems: ['disciplinar', 'uvoln'],
      },
      dismissal: {
        label: 'уволнение',
        phrases: ['uvolniha me', 'zapoved za uvolnenie', 'prekratiha mi dogovor'],
        stems: ['uvoln', 'prekrat', 'sakrat'],
      },
      unpaidSalary: {
        label: 'неплатено възнаграждение',
        phrases: ['ne mi plashtat zaplata', 'ne mi platiha zaplata', 'zabavena zaplata'],
        stems: ['zaplata', 'vaznagrazhdenie', 'plasht'],
      },
      sickLeave: {
        label: 'болничен',
        phrases: ['uvolnenie po vreme na bolnichen', 'bolnichen i uvolnenie'],
        stems: ['bolnichen'],
      },
      workplaceHarassment: {
        label: 'тормоз на работа',
        phrases: ['tormoz na rabota', 'shefa me zaplashva'],
        stems: ['tormoz', 'zaplash', 'unizh'],
      },
      workingWithoutContract: {
        label: 'работа без договор',
        phrases: ['rabota bez dogovor', 'bez trudov dogovor'],
        stems: ['dogovor', 'rabot'],
      },
    },
  },
  administrative: {
    label: 'Административен акт / институция',
    priority: 'high',
    strongPhrases: {
      'nakazatelno postanovlenie': 12,
      'vrachiha mi akt': 11,
      'akt ot politsiya': 10,
      'zapoved ot obshtina': 10,
      'srok za obzhalvane': 9,
    },
    coreTerms: {
      akt: 6,
      fish: 5,
      globa: 5,
      postanovlenie: 6,
      obshtina: 5,
      instituciya: 4,
      obzhalvane: 4,
    },
    supportingTerms: {
      zapoved: 3,
      srok: 3,
      narushenie: 3,
      politsiya: 2,
      kmet: 3,
    },
    exclusions: {
      'notarialen akt': -10,
      'akt za razhdane': -8,
    },
    subtypes: {
      penaltyDecree: {
        label: 'наказателно постановление',
        phrases: ['nakazatelno postanovlenie'],
        stems: ['postanovlenie'],
      },
      policeFine: {
        label: 'акт/фиш от полиция',
        phrases: ['akt ot politsiya', 'fish ot politsiya', 'globa ot politsiya'],
        stems: ['akt', 'fish', 'globa', 'polits'],
      },
      municipalOrder: {
        label: 'заповед от община',
        phrases: ['zapoved ot obshtina', 'akt ot obshtina'],
        stems: ['obshtina', 'kmet'],
      },
    },
  },
  criminal: {
    label: 'Полиция / наказателен казус',
    priority: 'high',
    strongPhrases: {
      'zadarzhaha me': 13,
      'arestuvaha me': 13,
      'vikaha me v politsiya': 10,
      'poluchih prizovka': 10,
      'dosadebno proizvodstvo': 11,
      'obvinenie sreshtu men': 11,
    },
    coreTerms: {
      arest: 7,
      zadarzh: 7,
      prizovka: 6,
      prokuratura: 6,
      razpit: 5,
      obvinenie: 6,
      prestaplenie: 5,
      zaplaha: 5,
    },
    supportingTerms: {
      politsiya: 3,
      protokol: 3,
      svidetel: 2,
      zhalba: 2,
    },
    exclusions: {},
    subtypes: {
      detention: {
        label: 'задържане/арест',
        phrases: ['zadarzhaha me', 'arestuvaha me'],
        stems: ['arest', 'zadarzh'],
      },
      summons: {
        label: 'призовка/разпит',
        phrases: ['poluchih prizovka', 'vikaha me v politsiya'],
        stems: ['prizovka', 'razpit'],
      },
      accusation: {
        label: 'обвинение',
        phrases: ['obvinenie sreshtu men', 'dosadebno proizvodstvo'],
        stems: ['obvinenie', 'dosadeb'],
      },
    },
  },
  family: {
    label: 'Семейно право',
    priority: 'normal',
    strongPhrases: {
      'domashno nasilie': 13,
      'roditelski prava': 10,
      'rezhim na lichni otnosheniya': 9,
      'iskam razvod': 9,
    },
    coreTerms: {
      razvod: 6,
      izdrazhka: 6,
      dete: 5,
      roditel: 5,
      nasilie: 6,
      brak: 4,
    },
    supportingTerms: {
      sad: 2,
      zasedanie: 3,
      zaplaha: 3,
    },
    exclusions: {},
    subtypes: {
      domesticViolence: {
        label: 'домашно насилие',
        phrases: ['domashno nasilie'],
        stems: ['nasilie', 'zaplash'],
      },
      divorce: {
        label: 'развод',
        phrases: ['iskam razvod', 'delo za razvod'],
        stems: ['razvod'],
      },
      childCustody: {
        label: 'родителски права/дете',
        phrases: ['roditelski prava', 'dete v risk'],
        stems: ['dete', 'roditel', 'izdrazhka'],
      },
    },
  },
  discrimination: {
    label: 'Дискриминация',
    priority: 'normal',
    strongPhrases: {
      'diskriminatsiya na rabota': 10,
      'otkazaha da me obsluzhat': 10,
      'komisiya za zashtita ot diskriminatsiya': 10,
    },
    coreTerms: {
      diskrimin: 7,
      etnos: 5,
      proizhod: 5,
      uvrezhdane: 5,
      religiya: 4,
      pol: 4,
    },
    supportingTerms: {
      obida: 2,
      tormoz: 3,
      kzd: 4,
      razlichno: 2,
    },
    exclusions: {},
    subtypes: {
      workplace: {
        label: 'дискриминация на работа',
        phrases: ['diskriminatsiya na rabota'],
        stems: ['rabot', 'diskrimin'],
      },
      serviceRefusal: {
        label: 'отказ на обслужване',
        phrases: ['otkazaha da me obsluzhat'],
        stems: ['otkaz', 'obsluzh'],
      },
    },
  },
  hateSpeech: {
    label: 'Омразна реч онлайн',
    priority: 'normal',
    strongPhrases: {
      'omrazna rech': 12,
      'ezik na omrazata': 12,
      'obidi online': 9,
      'kleveta vav facebook': 9,
      'zaplah online': 10,
    },
    coreTerms: {
      omraz: 7,
      facebook: 5,
      tiktok: 5,
      instagram: 5,
      kleveta: 5,
      obida: 4,
      rasist: 5,
      komentar: 3,
    },
    supportingTerms: {
      skrinshot: 3,
      link: 3,
      profil: 2,
      publikatsiya: 3,
      zaplaha: 3,
    },
    exclusions: {},
    subtypes: {
      threatOnline: {
        label: 'онлайн заплаха',
        phrases: ['zaplah online'],
        stems: ['zaplah'],
      },
      defamation: {
        label: 'клевета/обида онлайн',
        phrases: ['kleveta vav facebook', 'obidi online'],
        stems: ['kleveta', 'obida'],
      },
    },
  },
  property: {
    label: 'Имотен спор',
    priority: 'normal',
    strongPhrases: {
      'notarialen akt': 11,
      'imoten spor': 9,
      'dogovor za naem': 9,
      'ne mi vrashtat depozit': 10,
    },
    coreTerms: {
      imot: 6,
      notarialen: 6,
      naem: 5,
      depozit: 5,
      sobstvenost: 5,
      nasledstvo: 4,
    },
    supportingTerms: {
      dogovor: 3,
      sased: 3,
      skitsa: 3,
    },
    exclusions: {
      'trudov dogovor': -9,
    },
    subtypes: {
      rentDeposit: {
        label: 'наем/депозит',
        phrases: ['dogovor za naem', 'ne mi vrashtat depozit'],
        stems: ['naem', 'depozit'],
      },
      ownership: {
        label: 'собственост',
        phrases: ['notarialen akt'],
        stems: ['sobstvenost', 'notarialen', 'imot'],
      },
    },
  },
  consumer: {
    label: 'Потребителски спор',
    priority: 'normal',
    strongPhrases: {
      'online pokupka': 9,
      'ne mi vrashtat parite': 5,
      'otkazaha garantsiya': 10,
    },
    coreTerms: {
      pokupka: 5,
      garantsiya: 6,
      turgovets: 5,
      stoka: 4,
      defekt: 4,
      usluga: 4,
    },
    supportingTerms: {
      kasova: 3,
      belezhka: 3,
      faktura: 3,
      pari: 2,
    },
    exclusions: {
      zaplata: -8,
      depozit: -6,
    },
    subtypes: {
      onlinePurchase: {
        label: 'онлайн покупка',
        phrases: ['online pokupka'],
        stems: ['pokupka', 'turgovets'],
      },
      warranty: {
        label: 'гаранция',
        phrases: ['otkazaha garantsiya'],
        stems: ['garantsiya', 'defekt'],
      },
    },
  },
  civil: {
    label: 'Граждански спор',
    priority: 'normal',
    strongPhrases: {
      'ne mi vrashtat parite': 6,
      'dalzhat mi pari': 9,
      'dogovor za zaem': 10,
      'iskam obezshtetenie': 9,
    },
    coreTerms: {
      zaem: 6,
      razpiska: 6,
      dalg: 5,
      obezshtetenie: 5,
      vredi: 4,
      pari: 3,
    },
    supportingTerms: {
      dogovor: 2,
      svidetel: 2,
      sad: 2,
    },
    exclusions: {
      zaplata: -8,
      depozit: -6,
      garantsiya: -5,
    },
    subtypes: {
      debt: {
        label: 'заем/дълг',
        phrases: ['dogovor za zaem', 'dalzhat mi pari'],
        stems: ['zaem', 'dalg', 'razpiska'],
      },
      damages: {
        label: 'обезщетение',
        phrases: ['iskam obezshtetenie'],
        stems: ['obezshtetenie', 'vredi'],
      },
    },
  },
  booking: {
    label: 'Консултация',
    priority: 'normal',
    strongPhrases: {
      'iskam konsultatsiya': 9,
      'iskam chas': 9,
      'kak da se svarzha': 8,
      'iskam advokat': 7,
    },
    coreTerms: {
      konsultatsiya: 5,
      chas: 5,
      advokat: 4,
      kontakt: 4,
      kanthora: 4,
    },
    supportingTerms: {
      obadete: 2,
      sreshta: 3,
    },
    exclusions: {},
    subtypes: {},
  },
  pricing: {
    label: 'Въпрос за хонорар',
    priority: 'normal',
    strongPhrases: {
      'kolko struva': 10,
      'kakva e tsenata': 10,
      'advokatski honorar': 10,
    },
    coreTerms: {
      tsena: 5,
      honorar: 6,
      taksa: 4,
      struva: 5,
      bezplatno: 4,
    },
    supportingTerms: {
      konsultatsiya: 2,
      pari: 2,
    },
    exclusions: {},
    subtypes: {},
  },
  documents: {
    label: 'Документи / доказателства',
    priority: 'normal',
    strongPhrases: {
      'kakvi dokumenti tryabvat': 9,
      'kakvo da podgotvya': 8,
      'imam dokumenti': 6,
    },
    coreTerms: {
      dokument: 4,
      dokazatelstvo: 5,
      skrinshot: 4,
      svidetel: 4,
      dogovor: 2,
    },
    supportingTerms: {
      zapoved: 2,
      akt: 2,
      protokol: 2,
      email: 2,
      link: 2,
    },
    exclusions: {},
    subtypes: {},
  },
};

export const AMBIGUOUS_MONEY_QUESTION =
  'За да ви насоча правилно, уточнете за какви пари става дума - заплата, заем, онлайн покупка, наем/депозит, застраховка или друго?';
